### ISSUE TITLE
[Example] Segmentation fault occurred when running example on Linux

### ISSUE THREAD

**Issue by gaoruhao** [ni/adas-replay-hil-image-shim#2]
![image](https://user-images.githubusercontent.com/6160645/199630651-26c958e3-d3b3-4438-99e6-2f8a8a4e7a9c.png)
![image](https://user-images.githubusercontent.com/6160645/199630662-5612bdef-c201-4b32-b1ac-b6608ec830e1.png)

**Comment by arcvid** [comment]
<img width="316" alt="Screenshot 2022-11-02 at 9 08 27 AM" src="https://user-images.githubusercontent.com/99898758/199633765-1fa922e5-4d19-41b0-aadb-6df69f4576b0.png">

**Comment by anderson-v** [comment]
A PR for the fix is [here](https://github.com/ni/adas-replay-hil-image-shim/pull/3)

**Comment by arcvid** [comment]
1. Ubuntu 20.04 LTS
2. gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
3. Yes, we have the RDMA hardware and it is setup correctly because we use this for transport internally. What do you mean by the NI RDMA driver? I have the libnirdma.so in /lib/x86_64. 
@YangLiuNI please find the above details provided by Anderson

**Comment by arcvid** [comment]
@YangLiuNI please find the details provided by Anderson:

We can avoid the segfault by removing the `-shared` flag in CMakeLists.txt. The segfault is happening because the ImageSenderDemo is not an executable but a shared library. These flags are under the else statement for the IF(WIN32) which explains why you are able to run this on windows. Doing this creates a Make issue, where references can’t be found. I have attached the image here, seems like this is from libnirdma.so.1 which is a dependency of the libimagesender.so (ldd confirms it). 
1. Ubuntu 20.04 LTS
2. gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
3. Yes, we have the RDMA hardware and it is setup correctly because we use this for transport internally. What do you mean by the NI RDMA driver? I have the libnirdma.so in /lib/x86_64. 

![image](https://user-images.githubusercontent.com/99898758/199798789-ff1488f5-7d62-4f2e-a1e1-da4aa5f70f75.png)

**Comment by ericgross2** [comment]
> @YangLiuNI please find the details provided by Anderson:
> 
> We can avoid the segfault by removing the `-shared` flag in CMakeLists.txt. The segfault is happening because the ImageSenderDemo is not an executable but a shared library. These flags are under the else statement for the IF(WIN32) which explains why you are able to run this on windows. Doing this creates a Make issue, where references can’t be found. I have attached the image here, seems like this is from libnirdma.so.1 which is a dependency of the libimagesender.so (ldd confirms it).

Thanks for digging into the segfault. I don't think Linux compiles of that example had been tested.

Regarding the missing symbols, those are expected. Because the libnirdma library (that libimageSender depends on) has some LabVIEW-specific entrypoints in it, it imports some functionality from LabVIEW to support those. You have to add the linker flag **--allow-shlib-undefined** when linking the executable to cause it to allow unresolved symbols in dependent libraries to be ignored. Those symbols are only used if called from LabVIEW, so they are fine to be unresolved in this executable.

**Comment by YangLiuNI** [comment]
> > @YangLiuNI please find the details provided by Anderson:
> > We can avoid the segfault by removing the `-shared` flag in CMakeLists.txt. The segfault is happening because the ImageSenderDemo is not an executable but a shared library. These flags are under the else statement for the IF(WIN32) which explains why you are able to run this on windows. Doing this creates a Make issue, where references can’t be found. I have attached the image here, seems like this is from libnirdma.so.1 which is a dependency of the libimagesender.so (ldd confirms it).
> 
> Thanks for digging into the segfault. I don't think Linux compiles of that example had been tested.
> 
> Regarding the missing symbols, those are expected. Because the libnirdma library (that libimageSender depends on) has some LabVIEW-specific entrypoints in it, it imports some functionality from LabVIEW to support those. You have to add the linker flag **--allow-shlib-undefined** when linking the executable to cause it to allow unresolved symbols in dependent libraries to be ignored. Those symbols are only used if called from LabVIEW, so they are fine to be unresolved in this executable.

I checked on Linux but thought that crash is due to lacking of RDMA card on my testing VM, I applied @ericgross2 's suggestion to add the linker flag '--allow-shlib-undefined' and it works now.
